"""
Django settings for saulgadgets project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__ ))) 
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&_pcxw7qwh#0k5k4$gg3r4gq(#3849r7tt)gi3n35%vylx-@t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
root_path = environ.Path(__file__) - 2
print("root_path  ::::" + str(root_path)  )
#BASE_DIR = root_path

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Application definition

MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')
#MEDIA_URL = '/media/'
MEDIA_URL = 'http://localhost:8000/static/media/'

print("BASE_DIR=root_path",BASE_DIR)
env = environ.Env() # set default    values and casting DEBUG=(bool, False), DJANGO_ENV=(str, 'dev')
environ.Env.read_env(root_path('.env')) 

ALLOWED_HOSTS = []

# Cart settings
CART_SESSION_ID ='shopping_cart'
CART_SESSION_EXPIRATION_DAYS = 7    # 7 days
SESSION_COOKIE_SECURE = False
CART_SESSION_COOKIE_AGE = 86400  # 1 day


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core',
    'apps.store',
    'apps.cart'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saulgadgets.urls'

TEMPLATE_DEBUG = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.store.context_processors.menu_categories',
                'apps.core.context_processors.product_media',
                'apps.store.context_processors.product_media',

            ],
        },
    },
]

WSGI_APPLICATION = 'saulgadgets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # To access to db shell : ./manage.py dbshell
    'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'saulgadget-pgdb',
            'USER': 'postgres',
            'PASSWORD': 'root2023',
            'HOST': '127.0.0.1',
            'PORT': '5432'
        },
    'default_mysql': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'saulgadget_db',
        'USER': 'root', 
        'PASSWORD': 'root2023',
        'HOST': '127.0.0.1',  
        'PORT': '3306', 
        'OPTIONS': {
             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  
         }
        #python manage.py migrate
        #After running this command Django will automatically create the necessary tables 
        # such as auth_group, auth_user, auth_permission, etc. 
        # It will also create the tables which are defined in the models.py file.
        
    },
    #D:\Projets\py-django-vuejs-ecommerce-website\soulgadgets_3_6_4\saulgadgets\db.sqlite3
    'default_sqlite3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': root_path('db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'apps/core/static'),
    os.path.join(BASE_DIR, 'apps/store/static'),
    os.path.join(BASE_DIR, 'apps/cart/static'),
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'products/'),
    os.path.join(BASE_DIR, 'products/thumbnails/'),
]
CORS_ALLOW_ALL_ORIGINS = True
#MEDIA_ROOT = os.path.join(BASE_DIR,'media\\')
print("MEDIA_URL  ::::" + str(MEDIA_URL)  )

MEDIA_DIR = os.path.join(BASE_DIR,'media/products/thumbnails')
#PRODUCT_MEDIA_DIR = os.path.join(MEDIA_ROOT,'products/')
print("BASE_DIR  ::::" + str(BASE_DIR))
print("MEDIA_ROOT  ::::" + str(MEDIA_ROOT)  )
print("MEDIA_DIR  ::::" + str(MEDIA_DIR))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
