# Generated by Django 5.0.6 on 2024-06-27 21:06

from django.db import migrations, models
import autoslug.fields

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=autoslug.fields.AutoSlugField(editable=True, populate_from='title'), max_length=255, verbose_name='URL Slug')),
            ],
        ),
    ]
