# Generated by Django 5.0.6 on 2024-06-28 16:14

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=apps.store.models.defaultSlug, max_length=255, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=apps.store.models.defaultSlug, max_length=255, verbose_name='URL Slug'),
        ),
    ]
