# Generated by Django 5.0.6 on 2024-06-28 16:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=autoslug.fields.AutoSlugField(editable=True, populate_from='title'), max_length=255, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=autoslug.fields.AutoSlugField(editable=True, populate_from='title'), max_length=255, unique=True, verbose_name='URL Slug'),
        ),
    ]
