# Generated by Django 5.0.6 on 2024-06-29 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_slug_alter_product_slug'),
    ]

    operations = [

        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=255, unique=True, verbose_name='URL Slug'),
        ),
    ]
