# Generated by Django 5.0.6 on 2024-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='if_featured',
            field=models.BooleanField(default=False),
        ),
    ]
