# Generated by Django 5.0.6 on 2024-07-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_if_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='if_featured',
            new_name='is_featured',
        ),
    ]
