# Generated by Django 5.0.6 on 2024-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_brand_category_created_at_category_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
