# Generated by Django 5.0.6 on 2024-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_brand_code_alter_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oem',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(max_length=25),
        ),
    ]
