# Generated by Django 5.0.6 on 2024-07-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_oem_alter_product_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='code',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
